name: CMake tests for various platforms

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

env:
  ASEA_DUMP_C: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - os: windows-2025
            c_compiler: cl
            cpp_compiler: cl
            cmake_generator: Visual Studio 17 2022
          - os: windows-2025
            c_compiler: x86_64-w64-mingw32-gcc
            cpp_compiler: x86_64-w64-mingw32-g++
            cmake_generator: Ninja
          - os: ubuntu-22.04
            c_compiler: gcc
            cpp_compiler: g++
            cmake_generator: Ninja
          - os: ubuntu-22.04
            c_compiler: clang
            cpp_compiler: clang++
            cmake_generator: Ninja
          - os: ubuntu-24.04-arm
            c_compiler: clang
            cpp_compiler: clang++
            cmake_generator: Ninja
          - os: macos-15
            c_compiler: clang
            cpp_compiler: clang++
            cmake_generator: Ninja
          - os: macos-15
            c_compiler: clang
            cpp_compiler: clang++
            cmake_generator: Ninja
            extra_cmake_flags:
              - -DCMAKE_C_FLAGS="-target x86_64-apple-macos15"
              - -DCMAKE_CXX_FLAGS="-target x86_64-apple-macos15"

    steps:
    - uses: msys2/setup-msys2@v2
      if: runner.os == 'Windows' && matrix.c_compiler == 'x86_64-w64-mingw32-gcc'

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        "-G${{ matrix.cmake_generator }}"
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=RelWithDebInfo
        -DASEA_ENABLE_TESTING=1
        ${{ matrix.extra_cmake_flags }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }} --parallel 4

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --timeout 30 -j 4 --test-dir ${{ steps.strings.outputs.build-output-dir }}/tests --rerun-failed --output-on-failure --build-config RelWithDebInfo
      # FIXME: how do we exclude benchmarks when using ctest??